version: 2.1

jobs:
  build:
    docker:
      - image: circleci/android:api-29
    steps:
      - checkout
      - run:
          name: Analyze on SonarCloud
          command: ./gradlew build sonarqube
      - store_test_results:
          path: app/build/test-results
      - store_artifacts:
          path: app/build/reports
workflows:
  main:
    jobs:
      - build:
          context: SonarCloud