version: 2.1

jobs:
  build:
    docker:
      - image: circleci/android:api-29
    steps:
      - checkout
      - run:
          name: Build app
          command: ./gradlew build jacocoTestReport
      - run:
          name: Upload to SonarQube
          command: ./gradlew sonarqube

      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: app/build/reports
          destination: /reports
workflows:
  main:
    jobs:
      - build:
          context: SonarCloud